apiVersion: v1
kind: Service
metadata:
  name: svc-sample-ui
spec:
  selector:
    component: sample-ui
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-sample-ui
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      component: sample-ui
  template:
    metadata:
      labels:
        component: sample-ui
    spec:
      containers:
        - name: sample-ui
          image: microservicesampleacr.azurecr.io/clientappui:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:80;
            - name: apiRoutePath__service1Endpoint
              value: http://svc-sample-service1api
            - name: apiRoutePath__service2Endpoint
              value: http://svc-sample-service2api
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-sample-ui
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-sample-ui
  targetCPUUtilizationPercentage: 50 # target CPU utilization