apiVersion: v1
kind: Service
metadata:
  name: svc-sample-service1api
spec:
  selector:
    component: sample-service1api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443 
    targetPort: 443
    protocol: TCP
    name: https

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-sample-service1api
spec:
  replicas: 2
  selector:
    matchLabels:
      component: sample-service1api
  template:
    metadata:
      labels:
        component: sample-service1api
    spec:
      containers:
        - name: sample-service1api
          image: microservicesampleacr.azurecr.io/service1api:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: sample-db
                  key: connectionstring
            - name: apiRoutePath__workerServiceEndPoint
              value: http://svc-sample-workerservice
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
              limits:
                cpu: "0.10"
      imagePullSecrets:
        - name : acr-secret
